
import { VideoInfo } from '../types';

// This function simulates calling an AI to extract video information.
// In a real application, this would involve a backend service that
// uses a library to get metadata, then possibly uses Gemini
// to summarize the description or generate a title.
export const fetchVideoInfo = async (url: string): Promise<VideoInfo> => {
  console.log(`Analyzing URL: ${url}`);
  
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  // A simple check to return different mock data based on URL content
  if (url.includes('music')) {
    return {
      id: 'mock-music-id',
      title: 'Cosmic Grooves - A Lo-fi Journey',
      description: 'This is a mock description generated by our AI assistant. It summarizes the video as a relaxing mix of lo-fi hip hop beats perfect for studying, relaxing, or late-night coding sessions. Enjoy the cosmic vibes.',
      thumbnailUrl: 'https://picsum.photos/seed/music/560/315',
    };
  }

  if (url.trim().length < 15) {
      throw new Error("Invalid URL provided");
  }

  return {
    id: 'mock-tech-id',
    title: 'The Future of AI: A Tech Explained Special',
    description: 'A simulated AI-generated summary of a tech documentary. This video explores the rapid advancements in artificial intelligence, its potential impact on society, and what the future might hold for humanity and machines.',
    thumbnailUrl: 'https://picsum.photos/seed/tech/560/315',
  };
};
